name: QKD Verification CI

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y coq build-essential libblas-dev liblapack-dev

      - name: Install Python deps (editable)
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      # Генерация Coq-файла и сертификата
      - name: Generate Coq instance (b92_inst.v + certificate.json)
        run: |
          make gen
          test -f coq/Generated/b92_inst.v

      # Юнит-тест генератора (pytest)
      - name: Python tests (generator smoke test)
        run: |
          pytest -q

      # Быстрая компиляция одного файла без Makefile.coq
      - name: Quick-compile generated Coq file
        run: |
          make coq-quick

      # Полная сборка через coq_makefile (опционально)
      - name: Full Coq build (optional)
        run: |
          test -f coq/_CoqProject
          make coq
