name: QKD Verification CI

on: [push, pull_request]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Updated to a newer version for better reliability

      - name: Set up Coq
        run: sudo apt-get update && sudo apt-get install -y coq

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run Coq verification
        run: |
          make coq
          make pipeline PYTHON=python3